In [3]:
import numpy as np
import pandas as pd

In [5]:
data=pd.read_csv("/content/Social_Network_Ads.csv")

In [6]:
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [7]:
df=data.drop(['User ID'],axis=1)#removing unwanted column

In [8]:
df['Gender']=df['Gender'].apply({'Male':1,'Female':2}.get)

In [9]:
df.head()

Gender  Age  EstimatedSalary  Purchased
0       1   19            19000          0
1       1   35            20000          0
2       2   26            43000          0
3       2   27            57000          0
4       1   19            76000          0

In [10]:
x=df[['Gender','Age','EstimatedSalary']]
y=df['Purchased']

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.75)#75% of data for training and rest 25% data for testing

>creating ML model using KNN algorythm

In [12]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)#n_neighbors value of k-5

In [13]:
#training-.fit()
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [14]:
#prediction-.fit()
y_pred=knn.predict(x_test)

In [15]:
y_pred

array([0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0])

In [16]:
#calculating the accuracy of ML model
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
ac=accuracy_score(y_test,y_pred)

In [17]:
print(cm)

[[56  8]
 [10 26]]


In [18]:
print(ac)

0.82


#predicting result of purchase for a new customer


In [19]:
data_new={'Gender':1,'Age':20,'EstimatedSalary':27000,'Purchased':1}


In [20]:
index=[1]#coverting dict into dataframe,#serial number

In [21]:
my_data=pd.DataFrame(data_new,index)

In [22]:
my_data

Gender  Age  EstimatedSalary  Purchased
1       1   20            27000          1

In [23]:
x=df[['Gender','Age','EstimatedSalary']]
y=df['Purchased']

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.80)

In [25]:
from sklearn.neighbors import KNeighborsClassifier #creating a ML model
knn=KNeighborsClassifier(n_neighbors=10)#n_neighbors is value of k=10

In [26]:
#training-.fit()
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=10)

In [27]:
y_pred=knn.predict(x_test)#prediction-predict()

In [28]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
ac=accuracy_score(y_test,y_pred)

In [29]:
print(cm)

[[47  1]
 [13 19]]


In [30]:
print(ac)

0.825
