In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv('/content/insurance2.csv')

In [4]:
data.head()

age  sex     bmi  children  smoker  region      charges  insuranceclaim
0   19    0  27.900         0       1       3  16884.92400               1
1   18    1  33.770         1       0       2   1725.55230               1
2   28    1  33.000         3       0       2   4449.46200               0
3   33    1  22.705         0       0       1  21984.47061               0
4   32    1  28.880         0       0       1   3866.85520               1

In [5]:
x=data[['age','sex','bmi','children','smoker','region','charges']]
y=data['insuranceclaim']

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.80)

In [7]:
from sklearn.linear_model import LogisticRegression
logmodel=LogisticRegression()

In [8]:
logmodel.fit(x_train,y_train)

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [9]:
y_pred=logmodel.predict(x_test)

In [10]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
ac=accuracy_score(y_test,y_pred)

In [11]:
print(cm)

[[ 85  29]
 [ 16 138]]


In [12]:
print(ac)

0.832089552238806


>PCA

In [15]:
from sklearn.decomposition import PCA

In [29]:
pca=PCA(n_components=5)
x_reduced_train=pd.DataFrame(pca.fit_transform(x_train))
x_reduced_test=pd.DataFrame(pca.fit_transform(x_test))

In [30]:
x_train.shape

(1070, 7)

In [31]:
x_reduced_train.shape

(1070, 5)

In [32]:
x_test.shape

(268, 7)

In [33]:
x_reduced_test.shape

(268, 5)

In [34]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.80)

In [35]:
from sklearn.linear_model import LogisticRegression
logmodel=LogisticRegression()

In [36]:
logmodel.fit(x_reduced_train,y_train)

LogisticRegression()

In [37]:
new_predictions=logmodel.predict(x_reduced_test)

In [38]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,new_predictions)
ac=accuracy_score(y_test,new_predictions)

In [39]:
print(cm)

[[77 37]
 [97 57]]


In [40]:
print(ac)

0.5


>predicting result of claim for a new client

In [13]:
data_new={'age':45,'sex':1,'bmi':59,'children':2,'smoker':0,'region':1,'charges':32007.567,'insuranceclaim':1}

In [ ]:
index=[1]

In [ ]:
my_data=pd.DataFrame(data_new,index)

In [ ]:
my_data

age  sex  bmi  children  smoker  region    charges  insuranceclaim
1   45    1   59         2       0       1  32007.567               1

In [ ]:
x=data[['age','sex','bmi','children','smoker','region','charges']]
y=data['insuranceclaim']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.65)

In [ ]:
from sklearn.linear_model import LogisticRegression
logmodel=LogisticRegression()

In [ ]:
logmodel.fit(x_train,y_train)

LogisticRegression()

In [ ]:
y_pred=logmodel.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
ac=accuracy_score(y_test,y_pred)

In [ ]:
print(cm)

[[144  48]
 [ 42 235]]


In [ ]:
print(ac)

0.8081023454157783
